include:
  - board: nice_nano_v2
    shield: marz44w_dongle dongle_display oled_adapter_pro_micro_128x64
  - board: nice_nano_v2
    shield: marz44w_left
  - board: nice_nano_v2
    shield: marz44w_right
