# Copyright (c) 2025 Frank David Martínez Muñoz <mnesarco>
# SPDX-License-Identifier: MIT

file_format: "1"
id: marz44w
name: marz44w
type: shield
url: https://github.com/mnesarco/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - marz44w_left
  - marz44w_right
  - marz44w_dongle