"parse_config":
  "modifier_fn_map":
    "left_alt": "\u2387"
    "left_ctrl": "\u2388"
    "left_gui": "\u2318"
    "left_shift": "\u21E7"
    "right_alt": "r\u2387"
    "right_ctrl": "r\u2388"
    "right_gui": "r\u2318"
    "right_shift": "r\u21E7"
  "raw_binding_map":
    "&bootloader": "\u2699"
    "&bt BT_CLR": "\u16D2clr"
    "&bt BT_SEL 0": "\u16D20"
    "&bt BT_SEL 1": "\u16D21"
    "&bt BT_SEL 2": "\u16D22"
    "&bt BT_SEL 3": "\u16D23"
    "&bt BT_SEL 4": "\u16D24"
    "&bt BT_SEL 5": "\u16D25"
    "&caps_word": "cw"
    "&out OUT_BLE": "\u2192\u16D2"
    "&out OUT_TOG": "usb/\u16D2"
    "&out OUT_USB": "\u2192usb"
    "&t3p": "\u2234"
  "zmk_keycode_map":
    "A": "A"
    "B": "B"
    "BSPC": "\u232B"
    "C": "C"
    "CAPS": "\U0001F130"
    "CLEAR2": "clear2"
    "COMMA": ","
    "D": "D"
    "DEL": "del"
    "DOT": "."
    "DOWN": "\u2193"
    "E": "E"
    "END": "\u2198"
    "ESC": "esc"
    "F": "F"
    "F1": "f1"
    "F10": "f10"
    "F11": "f11"
    "F12": "f12"
    "F13": "f13"
    "F14": "f14"
    "F15": "f15"
    "F16": "f16"
    "F17": "f17"
    "F18": "f18"
    "F19": "f19"
    "F2": "f2"
    "F20": "f20"
    "F21": "f21"
    "F22": "f22"
    "F23": "f23"
    "F24": "f24"
    "F3": "f3"
    "F4": "f4"
    "F5": "f5"
    "F6": "f6"
    "F7": "f7"
    "F8": "f8"
    "F9": "f9"
    "G": "G"
    "GRAVE": "|"
    "H": "H"
    "HOME": "\u2196"
    "I": "I"
    "INS": "ins"
    "J": "J"
    "K": "K"
    "KP_ASTERISK": "k*"
    "KP_COMMA": "k,"
    "KP_DOT": "k."
    "KP_ENTER": "kent"
    "KP_EQUAL": "k="
    "KP_MINUS": "k-"
    "KP_N0": "k0"
    "KP_N1": "k1"
    "KP_N2": "k2"
    "KP_N3": "k3"
    "KP_N4": "k4"
    "KP_N5": "k5"
    "KP_N6": "k6"
    "KP_N7": "k7"
    "KP_N8": "k8"
    "KP_N9": "k9"
    "KP_NLCK": "nlck"
    "KP_PLUS": "k+"
    "KP_SLASH": "k/"
    "K_COPY": "\u2FFB"
    "K_CUT": "\u2702"
    "K_MUTE": "mute"
    "K_PASTE": "\u29C9"
    "K_PWR": "k_pwr"
    "K_REDO": "\u21B7"
    "K_UNDO": "\u21B6"
    "K_VOL_DN": "vol-"
    "K_VOL_UP": "vol+"
    "L": "L"
    "LALT": "\u2387"
    "LBKT": "\xB4"
    "LC(LA(DOWN))": "zw"
    "LCTRL": "\u2388"
    "LEFT": "\u2190"
    "LGUI": "\u2318"
    "LS(COMMA)": ";"
    "LS(DOT)": ":"
    "LS(EQL)": "\xBF"
    "LS(GRAVE)": "\xBA"
    "LS(LBRC)": "diae"
    "LS(MINUS)": "?"
    "LS(N0)": "="
    "LS(N1)": "!"
    "LS(N2)": "\""
    "LS(N3)": "#"
    "LS(N4)": "$"
    "LS(N5)": "%"
    "LS(N6)": "&"
    "LS(N7)": "/"
    "LS(N8)": "("
    "LS(N9)": ")"
    "LS(NUBS)": ">"
    "LS(NUHS)": "]"
    "LS(RBRC)": "*"
    "LS(SLASH)": "_"
    "LS(SQT)": "["
    "LSHIFT": "\u21E7"
    "M": "M"
    "MINUS": "'"
    "N": "N"
    "N0": "0"
    "N1": "1"
    "N2": "2"
    "N3": "3"
    "N4": "4"
    "N5": "5"
    "N6": "6"
    "N7": "7"
    "N8": "8"
    "N9": "9"
    "NUBS": "<"
    "NUHS": "}"
    "O": "O"
    "P": "P"
    "PAUSE_BREAK": "pause"
    "PG_UP": "\u21DF"
    "PIPE2": "|2"
    "PSCRN": "\u2399"
    "Q": "Q"
    "R": "R"
    "RA(A)": "\xE6"
    "RA(B)": "\u201D"
    "RA(C)": "\xA2"
    "RA(COMMA)": "\u2500"
    "RA(D)": "\xF0"
    "RA(E)": "\u20AC"
    "RA(F)": "\u0111"
    "RA(G)": "\u014B"
    "RA(GRAVE)": "\xAC"
    "RA(H)": "\u0127"
    "RA(J)": "\u02C0"
    "RA(L)": "\u0142"
    "RA(LBRC)": "\xA8"
    "RA(M)": "\xB5"
    "RA(MINUS)": "\\"
    "RA(N)": "n"
    "RA(N0)": "\xB8"
    "RA(N3)": "\xB7"
    "RA(N5)": "\xBD"
    "RA(NUHS)": "`"
    "RA(O)": "\xF8"
    "RA(P)": "\xFE"
    "RA(Q)": "@"
    "RA(R)": "\xB6"
    "RA(RBKT)": "~"
    "RA(S)": "\xDF"
    "RA(SQT)": "^"
    "RA(T)": "\u0167"
    "RA(V)": "\u201C"
    "RA(X)": "\xBB"
    "RA(Z)": "\xAB"
    "RA(k)": "\u0138"
    "RALT": "r\u2387"
    "RBKT": "+"
    "RCTRL": "r\u2388"
    "RET": "\u23CE"
    "RGUI": "r\u2318"
    "RIGHT": "\u2192"
    "RSHIFT": "r\u21E7"
    "S": "S"
    "SEMI": "\xF1"
    "SLASH": "-"
    "SLCK": "slck"
    "SPC": "\u2423"
    "SQT": "{"
    "SYS_PWR": "sys_pwr"
    "SYS_SLEEP": "sys_sleep"
    "SYS_WAKE": "sys_wake"
    "T": "T"
    "TAB": "\u21C4"
    "TILDE": "G~"
    "U": "U"
    "UP": "\u2191"
    "V": "V"
    "W": "W"
    "X": "X"
    "Y": "Y"
    "Z": "Z"
