layout: {zmk_keyboard: marz44w}
layers:
  DEF:
  - - {t: esc, h: ⌘}
    - Q
    - W
    - F
    - P
    - B
    - J
    - L
    - U
    - Y
    - ´
    - ñ
  - - {t: ⇄, h: ⎇}
    - {t: A, h: ⇧}
    - R
    - S
    - T
    - G
    - M
    - n
    - E
    - I
    - {t: O, h: ⇧}
    - cw
  - - {t: \, h: ⎈}
    - Z
    - X
    - C
    - D
    - V
    - K
    - H
    - ','
    - .
    - ;
    - ⏎
  - - {t: ⇄, h: NUM}
    - {t: ⌫, h: SYM1}
    - {t: ␣, h: NAV}
    - ⇧+⎇
    - r⎇
    - {t: ␣, h: NAV}
    - {t: ⌫, h: SYM1}
    - {t: del, h: ADJ}
  NUM:
  - - {t: ▽, type: trans}
    - '*'
    - '7'
    - '8'
    - '9'
    - /
    - /
    - '7'
    - '8'
    - '9'
    - '*'
    - ∴
  - [',', '0', '4', '5', '6', '-', '-', '4', '5', '6', '0', ',']
  - - zw
    - .
    - '1'
    - '2'
    - '3'
    - +
    - +
    - '1'
    - '2'
    - '3'
    - .
    - {t: ▽, type: trans}
  - - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  SYM1:
  - ['|', '!', '"', '#', $, '%', '&', /, '[', '\]', '=', '?']
  - - '|'
    - '*'
    - ''''
    - ':'
    - _
    - '-'
    - '-'
    - (
    - )
    - '{'
    - '}'
    - {t: ▽, type: trans}
  - - diae
    - '@'
    - '~'
    - ^
    - '='
    - +
    - +
    - ''''
    - <
    - '>'
    - \
    - {t: ▽, type: trans}
  - - ADJ
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: NUM, h: sticky}
    - {t: ▽, type: trans}
  NAV:
  - - {t: ▽, type: trans}
    - f1
    - f2
    - f3
    - f4
    - f5
    - {t: ▽, type: trans}
    - ⇟
    - ↑
    - ⇟
    - f10
    - f11
  - - {t: ▽, type: trans}
    - ⇧
    - ''''
    - ':'
    - _
    - '-'
    - ↖
    - ←
    - ↓
    - →
    - ↘
    - f12
  - - {t: ▽, type: trans}
    - f6
    - f7
    - f8
    - f9
    - f10
    - ⎈+↖
    - ⎈+←
    - ''
    - ⎈+→
    - ⎈+↘
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  ADJ:
  - - ⚙
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - ⚙
  - [ᛒclr, ᛒ0, ᛒ1, ᛒ2, ᛒ3, ᛒ4, ᛒ4, ᛒ3, ᛒ2, ᛒ1, ᛒ0, ᛒclr]
  - - {t: ▽, type: trans}
    - nlck
    - usb/ᛒ
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
  - - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {t: ▽, type: trans}
    - {type: held}
combos:
- p: [38, 41]
  k: zw
  l: [DEF]
